name: Deploy to Web Server

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Web Server
        run: |
          # Web Server এর IP address
          SERVER_USER=ubuntu
          SERVER_IP=18.143.176.43

          # কোড কপি করো Web Server এ
          scp -o StrictHostKeyChecking=no -r ./* $ubuntu@$18.143.176.43:/var/www/mywebsite/

          # Nginx restart
          ssh -o StrictHostKeyChecking=no $ubuntu@$18.143.176.43 "sudo systemctl restart nginx"
